
import { Canteen, FoodItem } from "./types";

export const mockCanteens: Canteen[] = [
  {
    id: "1",
    name: "Student Union Café",
    description: "Main campus café serving a variety of North Indian and South Indian meals.",
    image: "https://source.unsplash.com/random/800x600/?indian-restaurant",
    location: "Student Union Building, Ground Floor",
    contact: "+91-9876543210",
    openingHours: "Mon-Sat: 8:00 AM - 9:00 PM, Sun: 9:00 AM - 8:00 PM",
  },
  {
    id: "2",
    name: "Engineering Hub",
    description: "Quick bites and chai for busy engineering students.",
    image: "https://source.unsplash.com/random/800x600/?cafe-india",
    location: "Engineering Building, 2nd Floor",
    contact: "+91-8765432109",
    openingHours: "Mon-Sat: 8:30 AM - 6:30 PM, Sun: Closed",
  },
  {
    id: "3",
    name: "Arts Bistro",
    description: "Artistic atmosphere with organic and pure vegetarian options.",
    image: "https://source.unsplash.com/random/800x600/?vegetarian-indian",
    location: "Arts & Humanities Building, 1st Floor",
    contact: "+91-7654321098",
    openingHours: "Mon-Sat: 9:00 AM - 8:00 PM, Sun: 10:00 AM - 4:00 PM",
  },
  {
    id: "4",
    name: "Science Spot",
    description: "Healthy meals and fresh juices with late-night options during exam season.",
    image: "https://source.unsplash.com/random/800x600/?indian-street-food",
    location: "Science Complex, Lower Level",
    contact: "+91-6543210987",
    openingHours: "Mon-Sat: 7:30 AM - 10:00 PM, Sun: 8:00 AM - 9:00 PM",
  },
];

export const mockFoodItems: FoodItem[] = [
  // Student Union Café Items
  {
    id: "101",
    name: "Butter Chicken with Naan",
    description: "Creamy butter chicken served with 2 garlic naan",
    price: 150,
    image: "https://source.unsplash.com/random/800x600/?butter-chicken",
    category: "Main Course",
    isVegetarian: false,
    canteenId: "1",
  },
  {
    id: "102",
    name: "Paneer Wrap",
    description: "Fresh paneer tikka with mint chutney in a whole wheat wrap",
    price: 90,
    image: "https://source.unsplash.com/random/800x600/?paneer-wrap",
    category: "Main Course",
    isVegetarian: true,
    canteenId: "1",
  },
  {
    id: "103",
    name: "Chicken Biryani",
    description: "Aromatic basmati rice cooked with tender chicken pieces and special spices",
    price: 130,
    image: "https://source.unsplash.com/random/800x600/?biryani",
    category: "Main Course",
    isVegetarian: false,
    canteenId: "1",
  },
  {
    id: "104",
    name: "Chocolate Muffin",
    description: "Freshly baked chocolate chip muffin",
    price: 40,
    image: "https://source.unsplash.com/random/800x600/?muffin",
    category: "Dessert",
    isVegetarian: true,
    canteenId: "1",
  },
  {
    id: "105",
    name: "Masala Chai",
    description: "Traditional Indian spiced tea",
    price: 20,
    image: "https://source.unsplash.com/random/800x600/?masala-chai",
    category: "Beverage",
    isVegetarian: true,
    canteenId: "1",
  },

  // Engineering Hub Items
  {
    id: "201",
    name: "Aloo Paratha with Curd",
    description: "Stuffed potato paratha served with fresh curd",
    price: 70,
    image: "https://source.unsplash.com/random/800x600/?paratha",
    category: "Breakfast",
    isVegetarian: true,
    canteenId: "2",
  },
  {
    id: "202",
    name: "Rajma Chawal",
    description: "Kidney beans curry served with steamed rice",
    price: 110,
    image: "https://source.unsplash.com/random/800x600/?rajma-chawal",
    category: "Main Course",
    isVegetarian: true,
    canteenId: "2",
  },
  {
    id: "203",
    name: "Filter Coffee",
    description: "South Indian filter coffee",
    price: 30,
    image: "https://source.unsplash.com/random/800x600/?filter-coffee",
    category: "Beverage",
    isVegetarian: true,
    canteenId: "2",
  },
  {
    id: "204",
    name: "Chicken Kathi Roll",
    description: "Flaky paratha wrapped with spicy chicken tikka and mint chutney",
    price: 100,
    image: "https://source.unsplash.com/random/800x600/?kathi-roll",
    category: "Main Course",
    isVegetarian: false,
    canteenId: "2",
  },
  {
    id: "205",
    name: "Samosa",
    description: "Crispy pastry filled with spiced potatoes and peas",
    price: 25,
    image: "https://source.unsplash.com/random/800x600/?samosa",
    category: "Snack",
    isVegetarian: true,
    canteenId: "2",
  },

  // Arts Bistro Items
  {
    id: "301",
    name: "Poha",
    description: "Flattened rice tempered with mustard seeds, curry leaves, and peanuts",
    price: 60,
    image: "https://source.unsplash.com/random/800x600/?poha",
    category: "Breakfast",
    isVegetarian: true,
    canteenId: "3",
  },
  {
    id: "302",
    name: "Thali Special",
    description: "Complete meal with dal, sabzi, rice, roti, papad, and dessert",
    price: 180,
    image: "https://source.unsplash.com/random/800x600/?indian-thali",
    category: "Main Course",
    isVegetarian: true,
    canteenId: "3",
  },
  {
    id: "303",
    name: "Rose Milk",
    description: "Chilled milk flavored with rose syrup",
    price: 40,
    image: "https://source.unsplash.com/random/800x600/?rose-milk",
    category: "Beverage",
    isVegetarian: true,
    canteenId: "3",
  },
  {
    id: "304",
    name: "Saag Paneer with Roti",
    description: "Spinach curry with cottage cheese served with 3 rotis",
    price: 120,
    image: "https://source.unsplash.com/random/800x600/?saag-paneer",
    category: "Main Course",
    isVegetarian: true,
    canteenId: "3",
  },
  {
    id: "305",
    name: "Mango Lassi",
    description: "Yogurt-based drink blended with mango and sugar",
    price: 50,
    image: "https://source.unsplash.com/random/800x600/?mango-lassi",
    category: "Beverage",
    isVegetarian: true,
    canteenId: "3",
  },

  // Science Spot Items
  {
    id: "401",
    name: "Idli Sambar",
    description: "Steamed rice cakes served with lentil soup and coconut chutney",
    price: 80,
    image: "https://source.unsplash.com/random/800x600/?idli-sambar",
    category: "Breakfast",
    isVegetarian: true,
    canteenId: "4",
  },
  {
    id: "402",
    name: "Chole Bhature",
    description: "Spicy chickpea curry served with fried bread",
    price: 120,
    image: "https://source.unsplash.com/random/800x600/?chole-bhature",
    category: "Main Course",
    isVegetarian: true,
    canteenId: "4",
  },
  {
    id: "403",
    name: "Fresh Lime Soda",
    description: "Refreshing drink made with fresh lime juice, soda water, and sugar or salt",
    price: 35,
    image: "https://source.unsplash.com/random/800x600/?lime-soda",
    category: "Beverage",
    isVegetarian: true,
    canteenId: "4",
  },
  {
    id: "404",
    name: "Egg Fried Rice",
    description: "Basmati rice stir-fried with eggs, vegetables, and soy sauce",
    price: 100,
    image: "https://source.unsplash.com/random/800x600/?egg-fried-rice",
    category: "Main Course",
    isVegetarian: false,
    canteenId: "4",
  },
  {
    id: "405",
    name: "Besan Ladoo",
    description: "Sweet ball made from gram flour, ghee, and sugar",
    price: 30,
    image: "https://source.unsplash.com/random/800x600/?ladoo",
    category: "Dessert",
    isVegetarian: true,
    canteenId: "4",
  },
];

export const mockUsers = [
  {
    id: "user1",
    email: "student@university.edu",
    password: "password123",
    name: "Rahul Sharma",
    studentId: "S12345",
  },
];
