
import { Canteen, FoodItem } from "./types";

export const mockCanteens: Canteen[] = [
  {
    id: "1",
    name: "Student Union Café",
    description: "Main campus café serving a variety of meals and snacks.",
    image: "/assets/canteen1.jpg",
    location: "Student Union Building, Ground Floor",
    contact: "+1-555-123-4567",
    openingHours: "Mon-Fri: 7:30 AM - 9:00 PM, Sat-Sun: 9:00 AM - 7:00 PM",
  },
  {
    id: "2",
    name: "Engineering Hub",
    description: "Quick bites and coffee for busy engineering students.",
    image: "/assets/canteen2.jpg",
    location: "Engineering Building, 2nd Floor",
    contact: "+1-555-234-5678",
    openingHours: "Mon-Fri: 8:00 AM - 6:00 PM, Closed on weekends",
  },
  {
    id: "3",
    name: "Arts Bistro",
    description: "Artistic atmosphere with organic and vegan options.",
    image: "/assets/canteen3.jpg",
    location: "Arts & Humanities Building, 1st Floor",
    contact: "+1-555-345-6789",
    openingHours: "Mon-Fri: 9:00 AM - 8:00 PM, Sat: 10:00 AM - 4:00 PM, Sun: Closed",
  },
  {
    id: "4",
    name: "Science Spot",
    description: "Healthy meals and smoothies with late-night options during exam season.",
    image: "/assets/canteen4.jpg",
    location: "Science Complex, Lower Level",
    contact: "+1-555-456-7890",
    openingHours: "Mon-Fri: 7:00 AM - 10:00 PM, Sat-Sun: 8:00 AM - 8:00 PM",
  },
];

export const mockFoodItems: FoodItem[] = [
  // Student Union Café Items
  {
    id: "101",
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    price: 8.99,
    image: "/assets/burger.jpg",
    category: "Main Course",
    isVegetarian: false,
    canteenId: "1",
  },
  {
    id: "102",
    name: "Veggie Wrap",
    description: "Fresh vegetables and hummus in a whole grain wrap",
    price: 6.99,
    image: "/assets/veggie-wrap.jpg",
    category: "Main Course",
    isVegetarian: true,
    canteenId: "1",
  },
  {
    id: "103",
    name: "Grilled Chicken Salad",
    description: "Mixed greens with grilled chicken, croutons, and balsamic dressing",
    price: 9.99,
    image: "/assets/chicken-salad.jpg",
    category: "Main Course",
    isVegetarian: false,
    canteenId: "1",
  },
  {
    id: "104",
    name: "Chocolate Muffin",
    description: "Freshly baked chocolate chip muffin",
    price: 2.99,
    image: "/assets/choc-muffin.jpg",
    category: "Dessert",
    isVegetarian: true,
    canteenId: "1",
  },
  {
    id: "105",
    name: "Coffee",
    description: "Freshly brewed coffee",
    price: 2.49,
    image: "/assets/coffee.jpg",
    category: "Beverage",
    isVegetarian: true,
    canteenId: "1",
  },

  // Engineering Hub Items
  {
    id: "201",
    name: "Energy Breakfast Sandwich",
    description: "Egg, cheese, and bacon on a bagel",
    price: 5.99,
    image: "/assets/breakfast-sandwich.jpg",
    category: "Breakfast",
    isVegetarian: false,
    canteenId: "2",
  },
  {
    id: "202",
    name: "Protein Power Bowl",
    description: "Quinoa, chicken, avocado, and vegetables",
    price: 10.99,
    image: "/assets/protein-bowl.jpg",
    category: "Main Course",
    isVegetarian: false,
    canteenId: "2",
  },
  {
    id: "203",
    name: "Double Espresso",
    description: "Strong double shot of espresso",
    price: 3.49,
    image: "/assets/espresso.jpg",
    category: "Beverage",
    isVegetarian: true,
    canteenId: "2",
  },
  {
    id: "204",
    name: "Chicken Sandwich",
    description: "Grilled chicken with aioli and fresh vegetables",
    price: 7.99,
    image: "/assets/chicken-sandwich.jpg",
    category: "Main Course",
    isVegetarian: false,
    canteenId: "2",
  },
  {
    id: "205",
    name: "Energy Bar",
    description: "Protein-packed energy bar with nuts and dried fruits",
    price: 3.49,
    image: "/assets/energy-bar.jpg",
    category: "Snack",
    isVegetarian: true,
    canteenId: "2",
  },

  // Arts Bistro Items
  {
    id: "301",
    name: "Avocado Toast",
    description: "Whole grain toast with avocado, cherry tomatoes, and microgreens",
    price: 8.49,
    image: "/assets/avocado-toast.jpg",
    category: "Breakfast",
    isVegetarian: true,
    canteenId: "3",
  },
  {
    id: "302",
    name: "Mediterranean Platter",
    description: "Hummus, falafel, pita bread, and vegetable sticks",
    price: 11.99,
    image: "/assets/mediterranean.jpg",
    category: "Main Course",
    isVegetarian: true,
    canteenId: "3",
  },
  {
    id: "303",
    name: "Matcha Latte",
    description: "Organic matcha green tea with steamed milk",
    price: 4.99,
    image: "/assets/matcha.jpg",
    category: "Beverage",
    isVegetarian: true,
    canteenId: "3",
  },
  {
    id: "304",
    name: "Vegan Buddha Bowl",
    description: "Rice, roasted vegetables, tofu, and tahini dressing",
    price: 10.49,
    image: "/assets/buddha-bowl.jpg",
    category: "Main Course",
    isVegetarian: true,
    canteenId: "3",
  },
  {
    id: "305",
    name: "Berry Smoothie",
    description: "Mixed berries, banana, and almond milk",
    price: 5.49,
    image: "/assets/smoothie.jpg",
    category: "Beverage",
    isVegetarian: true,
    canteenId: "3",
  },

  // Science Spot Items
  {
    id: "401",
    name: "Brain Boost Breakfast Bowl",
    description: "Oatmeal with blueberries, walnuts, and honey",
    price: 6.49,
    image: "/assets/oatmeal.jpg",
    category: "Breakfast",
    isVegetarian: true,
    canteenId: "4",
  },
  {
    id: "402",
    name: "Study Buddy Pizza",
    description: "Personal pizza with your choice of three toppings",
    price: 9.99,
    image: "/assets/pizza.jpg",
    category: "Main Course",
    isVegetarian: false,
    canteenId: "4",
  },
  {
    id: "403",
    name: "Green Machine Smoothie",
    description: "Spinach, banana, pineapple, and protein powder",
    price: 5.99,
    image: "/assets/green-smoothie.jpg",
    category: "Beverage",
    isVegetarian: true,
    canteenId: "4",
  },
  {
    id: "404",
    name: "Late Night Noodles",
    description: "Ramen noodles with vegetables and your choice of protein",
    price: 8.49,
    image: "/assets/noodles.jpg",
    category: "Main Course",
    isVegetarian: false,
    canteenId: "4",
  },
  {
    id: "405",
    name: "Power Cookie",
    description: "Oatmeal cookie with dark chocolate chips and dried cranberries",
    price: 2.99,
    image: "/assets/cookie.jpg",
    category: "Dessert",
    isVegetarian: true,
    canteenId: "4",
  },
];

export const mockUsers = [
  {
    id: "user1",
    email: "student@university.edu",
    password: "password123",
    name: "John Doe",
    studentId: "S12345",
  },
];
